apiVersion: v1
kind: Template
metadata:
  name: ai-one
objects:
  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      name: ai-one
      namespace: onentai
      labels:
        app: ai-one
    spec:
      strategy:
        type: Rolling
        rollingParams:
          updatePeriodSeconds: 1
          intervalSeconds: 1
          timeoutSeconds: 600
          maxUnavailable: 25%
          maxSurge: 25%
        resources: {}
        activeDeadlineSeconds: 21600
      triggers:
        - type: ConfigChange
      replicas: 1
      test: false
      selector:
        app: ai-one
        deploymentconfig: ai-one
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: ai-one
            deploymentconfig: ai-one
        spec:
          containers:
            - name: ai-one
              image: '${REGISTRY_URL}'
              resources: {}
              imagePullPolicy: Always
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}
parameters:
- name: REGISTRY_URL
  displayName: OpenShift Container Registry
  description: URL of the container in Registry (baseUrl/container-name:version)
  required: true